name: Suggestion for an existing feature
description: Suggest a new feature/improvement for an existing feature in Harmlesse's Scripts.
title: "[ENHANCEMENT] "
labels: enhancement
body:
- type: textarea
  attributes:
    label: What feature is this suggestion for?
    description: Name of the current feature you are suggesting a improvement for.
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe the suggestion
    description: A clear description of what the suggestion is.
  validations:
    required: true
- type: textarea
  attributes:
    label: Why do you think this suggestion would be useful?
    description: A clear description of why you think this suggestion would be useful.
  validations:
    required: true
- type: textarea
  attributes:
    label: Where in the Menu should the feature be?
    description: Describe where in the Menu the feature should be.
    placeholder: |
      Example: Vehicle -> Fun Features
  validations:
    required: false
- type: textarea
  attributes:
    label: Additional context
    description: Add any other context or notes about the suggestion request here.
  validations:
    required: false
- type: checkboxes
  attributes:
    label: Feature
    description: Make sure that this suggestion IS NOT already implemented in Harmless's Scripts OR in YimMenu AND YimMenu Lua repository.
    options:
      - label: I've confirmed that this suggestion IS NOT already implemented.
        required: true
- type: checkboxes
  attributes:
    label: Version
    description: Make sure you are using the latest version of Harmlesse's Scripts and YimMenu.
    options:
      - label: I've confirmed that I am using the latest version.
        required: true