name: Suggest a new feature
description: Suggest a new feature you'd like to see added to Harmless's Scripts.
title: "[FEATURE REQUEST] "
labels: feature request
body:
- type: textarea
  attributes:
    label: What should the feature be called?
    description: Name of the feature you are suggesting.
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe the feature
    description: A clear description of what the feature should do.
  validations:
    required: true
- type: textarea
  attributes:
    label: Why do you think this feature would be useful?
    description: A clear description of why you think this feature would be useful.
  validations:
    required: true
- type: textarea
  attributes:
    label: List options for the feature
    description: List any options and what that said option should do.
    placeholder: |
      Example:
      - Enable feature [Toggle]
      - Spawn a vehicle [Button]
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional context
    description: Add any other context or notes about the feature here.
  validations:
    required: false
- type: checkboxes
  attributes:
    label: Existing script
    description: Make sure that this feature DOES NOT already exist in THIS repository OR in YimMenu AND YimMenu Lua repository.
    options:
      - label: I've confirmed that this script DOES NOT already exist.
        required: true